messageを作った
masato626/mas-frontend-basic-last-assignment pull request #2
Opened 2022-10-27 10:16 UTC by masato626

## セルフチェック
- [ ○] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ○] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [○ ] 記述の重複はないか
https://634e927e962233726ce0f18a-oiyinsivso.chromatic.com/?path=/story/molecules-message--message

2022-10-28 04:21 UTC, moe-backend commented
基本的な構造ができていて良いと思います！！
figmaを見るとタイトルテキストと説明テキストの間に余白があるので、その実装をお願いします！

2022-11-03 15:08 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
> +    flex: none;
ここから、flex-growまで消してしまって大丈夫です！コードに影響がないです！大変ですが、プロパティの意味を一つずつ着実に理解していきましょう！

2022-11-03 15:08 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
> +@use "../../variables" as *;
変数を定義するという項目覚えていますかね！カラーとかフォントサイズとか諸々、は（例）font-size: $font-sizeL;のように数値ではなく、定義した値を使った方がいいですね！設定したことがここで使えます！変数ははvariables.scssに書いたと思います！

2022-11-03 15:08 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
> +    flex: none;
ここも同様です

2022-11-07 05:21 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
>    padding-bottom: 10px;
一点だけ、少し細かいですが、兄弟要素の間はマージンの方がいいので、マージンボトムにしてください！今回の場合だとメッセージテキストとメッセージディーテールは兄弟なので、マージンの方がいいと思っています！

2022-11-07 05:21 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
>      padding-bottom: 6px;
こちらもです！

2022-11-07 05:27 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
>      padding-bottom: 6px;
ここはマージンボトムを使った方がいいです！少し細かいですが、メッセージテキストとメッセージディーテールは並列の関係（兄弟関係）なので、その間はマージンの方がいいです！
https://eclair.blog/difference-between-margin-and-padding/#:~:text=%E5%9F%BA%E6%9C%AC%E3%81%AF%E3%80%81%E8%A6%81%E7%B4%A0%E3%81%AE%E5%A4%96%E5%81%B4,%E8%BF%B7%E3%81%86%E3%81%93%E3%81%A8%E3%81%8C%E3%81%AA%E3%81%8F%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82

2022-11-07 05:27 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
>    padding-bottom: 10px;
こちらもです！

2022-11-07 05:28 UTC, airmo-ri-tennis commented on src/components/molecules/message/message.scss
>      padding-bottom: 6px;
https://csshtml.work/parent/#:~:text=%E8%A6%81%E7%B4%A0%E3%81%A8%E3%81%AF-,%E7%89%B9%E5%AE%9A%E3%81%AEhtml%E3%82%BF%E3%82%B0%E3%82%92%E5%9F%BA%E6%BA%96%E3%81%AB%E8%80%83%E3%81%88%E3%81%9F%E3%81%A8%E3%81%8D,%E5%BC%9F%E8%A6%81%E7%B4%A0%E3%80%8D%E3%81%A8%E5%91%BC%E3%81%B3%E3%81%BE%E3%81%99%E3%80%82

2022-11-13 00:00 UTC, MinamiHotta commented on src/components/atoms/button/button.scss
>  @use "../../variables" as *;
buttonのファイルがmessageブランチにもいるのが気になります。
各ブランチごとにコンポーネントを作成するので、今回はmessageのhtmlとscssのみ残すようお願いします。

2022-11-13 00:00 UTC, MinamiHotta commented on src/stories/molecules-message.stories.js
> +import Item_Message from "../components/molecules/message/message.html";
こちらも、Atoms_Messageがよいと思います。

2022-11-13 00:00 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  flex-grow: 0;
Yoshiharuさんのコメントにもあった通り、40～42行目は初期値と同様のため記述不要です。

2022-11-13 00:00 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  font-family: "Noto Sans JP";
font-familyもvaliablesの中に二種類あるので、どちらかを記述してください。

2022-11-13 00:00 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +@use "../../variables" as *;
すみません、こちら旧課題のつもりでお話されているようです。
新課題になってから自分でvaliablesを作成する機会はないのですが、なるべくこの中から探して書けるものは書くようにしましょう

2022-11-13 00:15 UTC, MinamiHotta reviewed
![image](https://user-images.githubusercontent.com/104500220/201499634-ab5159c6-db52-4af4-b0e6-d88832e73d40.png)
Figmaからも分かる通り、htmlの構造として、現在並列されている二つのものを囲むようにdivタグを設定し
<div class="message>
   <○○　class="messagetext"></○○>
   <○○　class="messagedetail"></○○>
</div>
とするのがよいです。

また、一か所で指摘された内容が、他の箇所でも修正しなければならないことも多々あるので、慎重に確認した上でレビュー依頼お願いします🔥

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  text-align: center;
こちら、text-align:centerだけで真ん中によるので、flex指定は不要です。
なので10～11行目は削除できます。

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  font-family: "Noto Serif JP";
valiablesの中に適切なスタイルがあると思います！

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  font-style: normal;
初期値がnormalなので不要です。

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  font-weight: 400;
こちらもYoshiharuさんが指摘されていると思いますが、初期値が400なので不要です。

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  font-size: 36px;
こちらも$fontsize-○○の形で記述しましょう

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  color: $black;
初期値がblackなので記述不要です

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +.messagedetail {
子要素のscssは親要素の中に記述できると、親要素で設定した中央寄せ等の設定が子要素にまで反映されるのでお得です。
なので、今回は外側にdiv要素を追加して、中にtextとdetailを並列させるように記載し、
.(div要素のクラス){
　   .messagetext{
       }
      .messagedetail{
       }
}
とできるとよいです

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  height: 54px;
butttonのときはやむを得なかったのですが、widthとheightを固定値で設定するのは避けましょう。
今回は、主にpaddingの設定のみで見本の通りに作成できます。いろいろ試してみてください！

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  flex-grow: 0;
14～16行目も不要です。

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +    height: 30px;
こちらのwidthとheightも同様です

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  text-align: center;
親要素の中に入れてしまえば、こちらの記述は不要となります

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.html
> +<div class="messagetext">タイトルテキスト</div>
h2タグが望ましいです。
divタグだらけになると見にくいためです。
見出しのタグについて、検索してみましょう。

2022-11-13 00:15 UTC, MinamiHotta commented on src/components/molecules/message/message.html
> +<div class="messagedetail">説明テキスト</div>
本文に適したタグに変更して下さい。

2022-11-13 00:40 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/201500142-4b0b25b1-d1c9-402d-bd5b-d7b725b531a6.png)
![image](https://user-images.githubusercontent.com/104500220/201500156-1bb43b9f-be76-4e59-bd27-547df5721b82.png)

いずれも縦方向に揃っていないようなので、margin:auto等を見直してみてください。

2022-11-17 23:21 UTC, AyumuTaoka commented
タイトルのfont-weightを確認してみてください！

2022-11-25 00:38 UTC, moe-backend commented on src/components/molecules/message/message.html
> +<div class="text">
このtextに対して、lgのとき上下52px 左右20pxのpadding、mdのとき上下32px 左右20pxのpaddingを設定するとうまくいくと思います！！

2022-12-02 03:14 UTC, MinamiHotta commented
![Uploading image.png…]()
デフォルトでついているmargingが不要なので`margin-bottom: 0`で打ち消してください

2022-12-02 04:07 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  padding-top: 52px, 20px, 52px;
こちらですが`padding-top`の記述になっているので全くpaddingが効いていません。正しくは`padding：`です

2022-12-02 04:08 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/205212790-9e69bdee-66b7-4108-aa06-f7ecbf9909bb.png)
![image](https://user-images.githubusercontent.com/104500220/205212880-b87cc9ac-0bc1-4097-a156-87288033c99c.png)

こちら、横幅が見本よりずいぶんおおきくなってしまっているので直したいです。原因究明中です...。

2022-12-02 05:27 UTC, higashiji2000 commented
横幅親要素の幅と同じになるのは、divのデフォルトであるblock要素の基本的な挙動かと思われます。
今回の課題では親要素の幅に広がる状態で問題ないので、修正は不要です！
仮に直す場合は、それぞれの要素に、 `width: fit-content`　の指定をするとテキストの幅になると思います。
display参考：https://saruwakakun.com/html-css/basic/display

2022-12-03 14:34 UTC, higashiji2000 requested changes
messageコンポーネントの見た目はいい感じです！
このままマージするとまずい箇所があったので、確認お願いします 🌭

2022-12-03 14:34 UTC, higashiji2000 commented on src/components/molecules/message/message.html
> +<div class="text">
一番外側の要素のクラス名としては、作成中のコンポーネントの名前と合わせた方が管理しやすそうです。
（今回であれば、`message`）

2022-12-03 14:34 UTC, higashiji2000 commented on src/components/molecules/message/message.html
> +  <h2 class="messagetext">タイトルテキスト</h2>
クラス名は基本的にケバブケースで書いていきましょう

2022-12-03 14:34 UTC, higashiji2000 commented on src/components/atoms/button/button.html
> -<a class="button">btn-text</a>
こちらをはじめとするボタン関連のファイルの削除がコミットされてしまっているので、このままマージすると以前 atoms-button. ブランチで作成したボタンが消えちゃうと思います。
そのため、最新のmasterに存在するbuttonをこのブランチに持ってくるという作業を行いたいです。

ターミナルでこのブランチ (molecules-message) にいることを確認して
```
git pull origin master
```
で最新のmasterをマージしましょう。
その際、最新のmasterではbuttonが追加され、molecules-messageブランチでは削除されているのでコンフリクトが起こると思います。
その際は、masterの側の変更 (incoming change)を残すようにしてください。

pullおよびコンフリクトの解消が終わったら、再度pushしてください。

コンフリクトは慣れるまで恐ろしく感じるものですが、ただどちらを残すか選択するだけです。
困ったら講師に相談してください！

2022-12-10 05:10 UTC, higashiji2000 commented
修正内容はいい感じです！

https://github.com/masato626/mas-frontend-basic-last-assignment/pull/2#discussion_r1038783878
↑こちらの内容が治ってなかったので確認をお願いしたいです！
難しそうであれば今日の定例か明日のミニブートキャンプきていただければ対応します 🙌

2022-12-10 12:48 UTC, higashiji2000 approved these changes
LGTMです 🐶 

DS_Storeが気になったらこちらを見てみてください！
https://playground.wraptas.site/78bd393f4bb84f2fbfe4d92bf86c5ee5

2022-12-10 13:10 UTC, merged