Organisms news
masato626/mas-frontend-basic-last-assignment pull request #5
Opened 2023-01-19 09:51 UTC by masato626

## セルフチェック
- [○ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ○] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [○ ] 記述の重複はないか
https://634e927e962233726ce0f18a-sevrzbtzbx.chromatic.com/?path=/story/organisms-news--news

2023-01-20 17:12 UTC, SakaueYae reviewed
![image](https://user-images.githubusercontent.com/101164626/213761170-3af79988-3f6d-4e6f-9748-2b000641193e.png)
hoverしていないときに下線が表示されているため、修正お願いします！

2023-01-23 15:23 UTC, renyagi commented on src/components/organisms/news/news.scss
> +      padding: 19px 30px 19px 20px;
padding:20px; で統一してしまって構わないと思います！

2023-01-25 02:46 UTC, higashiji2000 requested changes
二点修正お願いします！

2023-01-25 02:46 UTC, higashiji2000 commented on src/components/organisms/news/news.html
> +      <li class="news-content">
> HTML の `<li>` 要素は、リストの項目を表すために用いられます。この要素は、その項目が属する順序付きリスト ([`<ol>`](https://developer.mozilla.org/ja/docs/Web/HTML/Element/ol))、順序なしリスト ([`<ul>`](https://developer.mozilla.org/ja/docs/Web/HTML/Element/ul))、メニュー ([`<menu>`](https://developer.mozilla.org/ja/docs/Web/HTML/Element/menu)) のいずれかの子要素として配置する必要があります。

[MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/li)にはこのように書かれているので、liはulの直下に配置するようにしてください！
```suggestion
  <ul class="news-contents">
      <li class="news-content">
        <a href="#" class="news-content-link">
```
こんな感じになるかと思います。（scssの修正も必要になるかもです）

2023-01-25 02:46 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +}
```suggestion
  }
  .information-list {
  text-align: right;
  margin-top: 30px;
  .news-and-events-more {
    margin-top: 0;
    }
  }
}
```
`.information-list` は HTMLの構造上 `.news` の中に入っていると思うので、Scssでもその構造を反映させるようにしましょう。

2023-01-28 12:19 UTC, MoAI522 approved these changes
LGTM

2023-01-28 12:20 UTC, merged